import {TABLESTATE} from "@prisma/client"
export const restaurantTable = [
    {
        code:'KÖE-ALA-1',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:1
    },
    {
        code:'KÖE-ALA-2',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:1
    },
    {
        code:'KÖE-ALA-3',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:1
    },
    {
        code:'KÖE-ALA-4',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:1
    },
    {
        code:'KÖE-ALA-5',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:1
    },
    {
        code:'KÖE-ALA-6',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:1
    },
    {
        code:'KÖE-HER-1',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:2
    },
    {
        code:'KÖE-HER-2',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:2
    },
    {
        code:'KÖE-HER-3',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:2
    },
    {
        code:'KÖE-HER-4',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:2
    },
    {
        code:'KÖE-HER-5',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:2
    },
    {
        code:'KÖE-HER-6',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:2
    },
    {
        code:'KÖE-SJ-1',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:3
    },
    {
        code:'KÖE-SJ-2',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:3
    },
    {
        code:'KÖE-SJ-3',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:3
    },
    {
        code:'KÖE-SJ-4',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:3
    },
    {
        code:'KÖE-SJ-5',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:3
    },
    {
        code:'KÖE-SJ-6',
        capacity:4,
        state:TABLESTATE.FREE,
        idRestaurant:3
    },
]