import { USERTYPE } from "@prisma/client";
export const user = [
  {
    id: 207890254,
    userType: USERTYPE.ADMIN,
    name: "Erick",
    lastname: "Rojas",
    email: "admin@gmail.com",
    password: "$2b$10$mvxj5vK2BMHssoteUg4izOZUPaBEx1Um28lMp/doJAea7couFnyQW",
    state: true,
  },
  {
    id: 105820157,
    userType: USERTYPE.WAITER,
    name: "Kevin",
    lastname: "Sequeira",
    email: "waiter1@gmail.com",
    password: "$2b$10$mvxj5vK2BMHssoteUg4izOZUPaBEx1Um28lMp/doJAea7couFnyQW",
    idRestaurant: 1,
    state: true,
  },
  {
    id: 106590851,
    userType: USERTYPE.WAITER,
    name: "Oscar",
    lastname: "Saborio",
    email: "waiter2@gmail.com",
    password: "$2b$10$mvxj5vK2BMHssoteUg4izOZUPaBEx1Um28lMp/doJAea7couFnyQW",
    idRestaurant: 2,
    state: true,
  },
  {
    id: 109590856,
    userType: USERTYPE.WAITER,
    name: "Sonia",
    lastname: "Esquivel",
    email: "waiter3@gmail.com",
    password: "$2b$10$mvxj5vK2BMHssoteUg4izOZUPaBEx1Um28lMp/doJAea7couFnyQW",
    idRestaurant: 3,
    state: true,
  },
  {
    id: 208850224,
    userType: USERTYPE.USER,
    name: "Vinicio",
    lastname: "Picado",
    email: "usuario@gmail.com",
    password: "$2b$10$mvxj5vK2BMHssoteUg4izOZUPaBEx1Um28lMp/doJAea7couFnyQW",
    state: true,
  },
  {
    id: 203660124,
    userType: USERTYPE.USER,
    name: "Steven",
    lastname: "Garita",
    email: "usuario2@gmail.com",
    password: "$2b$10$mvxj5vK2BMHssoteUg4izOZUPaBEx1Um28lMp/doJAea7couFnyQW",
    state: true,
  },
  {
    id: 208150797,
    userType: USERTYPE.USER,
    name: "Gabriel",
    lastname: "Arias",
    email: "usuario3@gmail.com",
    password: "$2b$10$mvxj5vK2BMHssoteUg4izOZUPaBEx1Um28lMp/doJAea7couFnyQW",
    state: true,
  },
];
